# Generated by Django 4.1.2 on 2023-04-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
